export const DRAW_ELEMENTS = 'DRAW_ELEMENTS';
export const SELECT_TOOL = 'SELECT_TOOL';
export const SET_TRANSFORMER_VISIBILITY = 'SET_TRANSFORMER_VISIBILITY';
export const SELECT_ELEMENT = 'SELECT_ELEMENT';
export const CLEAN_BOARD = 'CLEAN_BOARD';